/**
 * Azure Machine Learning - Text Analytics
 * The Text Analytics API is a suite of text analytics web services built with Azure Machine Learning.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://azure.microsoft.com/en-us/documentation/articles/machine-learning-apps-text-analytics/
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.pontis.hackathon.textanalytics.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * DetectedLanguageV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T16:43:13.271+02:00")
public class DetectedLanguageV2   {
  @SerializedName("name")
  private String name = null;

  @SerializedName("iso6391Name")
  private String iso6391Name = null;

  @SerializedName("score")
  private Double score = null;

  public DetectedLanguageV2 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Long name of a detected language (e.g. English, French).
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "Long name of a detected language (e.g. English, French).")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DetectedLanguageV2 iso6391Name(String iso6391Name) {
    this.iso6391Name = iso6391Name;
    return this;
  }

   /**
   * A two letter representation of the detected language according to the ISO 639-1 standard (e.g. en, fr).
   * @return iso6391Name
  **/
  @ApiModelProperty(example = "null", value = "A two letter representation of the detected language according to the ISO 639-1 standard (e.g. en, fr).")
  public String getIso6391Name() {
    return iso6391Name;
  }

  public void setIso6391Name(String iso6391Name) {
    this.iso6391Name = iso6391Name;
  }

  public DetectedLanguageV2 score(Double score) {
    this.score = score;
    return this;
  }

   /**
   * A confidence score between 0 and 1. Scores close to 1 indicate 100% certainty that the identified language is true.
   * @return score
  **/
  @ApiModelProperty(example = "null", value = "A confidence score between 0 and 1. Scores close to 1 indicate 100% certainty that the identified language is true.")
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetectedLanguageV2 detectedLanguageV2 = (DetectedLanguageV2) o;
    return Objects.equals(this.name, detectedLanguageV2.name) &&
        Objects.equals(this.iso6391Name, detectedLanguageV2.iso6391Name) &&
        Objects.equals(this.score, detectedLanguageV2.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, iso6391Name, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetectedLanguageV2 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    iso6391Name: ").append(toIndentedString(iso6391Name)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

