/**
 * Azure Machine Learning - Text Analytics
 * The Text Analytics API is a suite of text analytics web services built with Azure Machine Learning.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://azure.microsoft.com/en-us/documentation/articles/machine-learning-apps-text-analytics/
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.pontis.hackathon.textanalytics.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * KeyPhraseBatchResultItemV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T16:43:13.271+02:00")
public class KeyPhraseBatchResultItemV2   {
  @SerializedName("keyPhrases")
  private List<String> keyPhrases = new ArrayList<String>();

  @SerializedName("id")
  private String id = null;

  public KeyPhraseBatchResultItemV2 keyPhrases(List<String> keyPhrases) {
    this.keyPhrases = keyPhrases;
    return this;
  }

  public KeyPhraseBatchResultItemV2 addKeyPhrasesItem(String keyPhrasesItem) {
    this.keyPhrases.add(keyPhrasesItem);
    return this;
  }

   /**
   * A list of representative words or phrases. The number of key phrases returned is proportional to the number of words in the input document.
   * @return keyPhrases
  **/
  @ApiModelProperty(example = "null", value = "A list of representative words or phrases. The number of key phrases returned is proportional to the number of words in the input document.")
  public List<String> getKeyPhrases() {
    return keyPhrases;
  }

  public void setKeyPhrases(List<String> keyPhrases) {
    this.keyPhrases = keyPhrases;
  }

  public KeyPhraseBatchResultItemV2 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique document identifier.
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "Unique document identifier.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyPhraseBatchResultItemV2 keyPhraseBatchResultItemV2 = (KeyPhraseBatchResultItemV2) o;
    return Objects.equals(this.keyPhrases, keyPhraseBatchResultItemV2.keyPhrases) &&
        Objects.equals(this.id, keyPhraseBatchResultItemV2.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyPhrases, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyPhraseBatchResultItemV2 {\n");
    
    sb.append("    keyPhrases: ").append(toIndentedString(keyPhrases)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

