/**
 * Azure Machine Learning - Text Analytics
 * The Text Analytics API is a suite of text analytics web services built with Azure Machine Learning.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://azure.microsoft.com/en-us/documentation/articles/machine-learning-apps-text-analytics/
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.pontis.hackathon.textanalytics.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;
import org.pontis.hackathon.textanalytics.client.model.OperationProcessingResult;


/**
 * OperationResult
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T16:43:13.271+02:00")
public class OperationResult   {
  /**
   * Operation status.
   */
  public enum StatusEnum {
    @SerializedName("notStarted")
    NOTSTARTED("notStarted"),
    
    @SerializedName("running")
    RUNNING("running"),
    
    @SerializedName("failed")
    FAILED("failed"),
    
    @SerializedName("cancelled")
    CANCELLED("cancelled"),
    
    @SerializedName("succeeded")
    SUCCEEDED("succeeded");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("createdDateTime")
  private DateTime createdDateTime = null;

  @SerializedName("lastActionDateTime")
  private DateTime lastActionDateTime = null;

  @SerializedName("operationType")
  private String operationType = null;

  @SerializedName("operationProcessingResult")
  private OperationProcessingResult operationProcessingResult = null;

  @SerializedName("message")
  private String message = null;

  public OperationResult status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Operation status.
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "Operation status.")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public OperationResult createdDateTime(DateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Operation creation date time (ISO 8601 literal).
   * @return createdDateTime
  **/
  @ApiModelProperty(example = "null", value = "Operation creation date time (ISO 8601 literal).")
  public DateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public OperationResult lastActionDateTime(DateTime lastActionDateTime) {
    this.lastActionDateTime = lastActionDateTime;
    return this;
  }

   /**
   * Operation last status change date time (ISO 8601 literal).
   * @return lastActionDateTime
  **/
  @ApiModelProperty(example = "null", value = "Operation last status change date time (ISO 8601 literal).")
  public DateTime getLastActionDateTime() {
    return lastActionDateTime;
  }

  public void setLastActionDateTime(DateTime lastActionDateTime) {
    this.lastActionDateTime = lastActionDateTime;
  }

  public OperationResult operationType(String operationType) {
    this.operationType = operationType;
    return this;
  }

   /**
   * Name of API endpoint that created the operation.
   * @return operationType
  **/
  @ApiModelProperty(example = "null", value = "Name of API endpoint that created the operation.")
  public String getOperationType() {
    return operationType;
  }

  public void setOperationType(String operationType) {
    this.operationType = operationType;
  }

  public OperationResult operationProcessingResult(OperationProcessingResult operationProcessingResult) {
    this.operationProcessingResult = operationProcessingResult;
    return this;
  }

   /**
   * Operation result. Specific format varies according to the operation type. Exists only in case the operation has reached a 'Succeeded' state.
   * @return operationProcessingResult
  **/
  @ApiModelProperty(example = "null", value = "Operation result. Specific format varies according to the operation type. Exists only in case the operation has reached a 'Succeeded' state.")
  public OperationProcessingResult getOperationProcessingResult() {
    return operationProcessingResult;
  }

  public void setOperationProcessingResult(OperationProcessingResult operationProcessingResult) {
    this.operationProcessingResult = operationProcessingResult;
  }

  public OperationResult message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Error message. Exists only in case the operation has reached a 'Failed' state.
   * @return message
  **/
  @ApiModelProperty(example = "null", value = "Error message. Exists only in case the operation has reached a 'Failed' state.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationResult operationResult = (OperationResult) o;
    return Objects.equals(this.status, operationResult.status) &&
        Objects.equals(this.createdDateTime, operationResult.createdDateTime) &&
        Objects.equals(this.lastActionDateTime, operationResult.lastActionDateTime) &&
        Objects.equals(this.operationType, operationResult.operationType) &&
        Objects.equals(this.operationProcessingResult, operationResult.operationProcessingResult) &&
        Objects.equals(this.message, operationResult.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, createdDateTime, lastActionDateTime, operationType, operationProcessingResult, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationResult {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    lastActionDateTime: ").append(toIndentedString(lastActionDateTime)).append("\n");
    sb.append("    operationType: ").append(toIndentedString(operationType)).append("\n");
    sb.append("    operationProcessingResult: ").append(toIndentedString(operationProcessingResult)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

