/**
 * Azure Machine Learning - Text Analytics
 * The Text Analytics API is a suite of text analytics web services built with Azure Machine Learning.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://azure.microsoft.com/en-us/documentation/articles/machine-learning-apps-text-analytics/
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.pontis.hackathon.textanalytics.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.pontis.hackathon.textanalytics.client.model.InputV2;


/**
 * TopicDetectionInputV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T16:43:13.271+02:00")
public class TopicDetectionInputV2   {
  @SerializedName("stopWords")
  private List<String> stopWords = new ArrayList<String>();

  @SerializedName("topicsToExclude")
  private List<String> topicsToExclude = new ArrayList<String>();

  @SerializedName("documents")
  private List<InputV2> documents = new ArrayList<InputV2>();

  public TopicDetectionInputV2 stopWords(List<String> stopWords) {
    this.stopWords = stopWords;
    return this;
  }

  public TopicDetectionInputV2 addStopWordsItem(String stopWordsItem) {
    this.stopWords.add(stopWordsItem);
    return this;
  }

   /**
   * List of words to ignore from all documents during pre-processing.
   * @return stopWords
  **/
  @ApiModelProperty(example = "null", value = "List of words to ignore from all documents during pre-processing.")
  public List<String> getStopWords() {
    return stopWords;
  }

  public void setStopWords(List<String> stopWords) {
    this.stopWords = stopWords;
  }

  public TopicDetectionInputV2 topicsToExclude(List<String> topicsToExclude) {
    this.topicsToExclude = topicsToExclude;
    return this;
  }

  public TopicDetectionInputV2 addTopicsToExcludeItem(String topicsToExcludeItem) {
    this.topicsToExclude.add(topicsToExcludeItem);
    return this;
  }

   /**
   * List of topics to omit from the response.
   * @return topicsToExclude
  **/
  @ApiModelProperty(example = "null", value = "List of topics to omit from the response.")
  public List<String> getTopicsToExclude() {
    return topicsToExclude;
  }

  public void setTopicsToExclude(List<String> topicsToExclude) {
    this.topicsToExclude = topicsToExclude;
  }

  public TopicDetectionInputV2 documents(List<InputV2> documents) {
    this.documents = documents;
    return this;
  }

  public TopicDetectionInputV2 addDocumentsItem(InputV2 documentsItem) {
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Get documents
   * @return documents
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InputV2> getDocuments() {
    return documents;
  }

  public void setDocuments(List<InputV2> documents) {
    this.documents = documents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopicDetectionInputV2 topicDetectionInputV2 = (TopicDetectionInputV2) o;
    return Objects.equals(this.stopWords, topicDetectionInputV2.stopWords) &&
        Objects.equals(this.topicsToExclude, topicDetectionInputV2.topicsToExclude) &&
        Objects.equals(this.documents, topicDetectionInputV2.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stopWords, topicsToExclude, documents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopicDetectionInputV2 {\n");
    
    sb.append("    stopWords: ").append(toIndentedString(stopWords)).append("\n");
    sb.append("    topicsToExclude: ").append(toIndentedString(topicsToExclude)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

