/**
 * Azure Machine Learning - Text Analytics
 * The Text Analytics API is a suite of text analytics web services built with Azure Machine Learning.   The API can be used to analyze unstructured text for tasks such as sentiment analysis, key phrase extraction and language detection.   No training data is needed to use this API; just bring your text data.   This API uses advanced natural language processing techniques to deliver best in class predictions.    Further documentation can be found in https://azure.microsoft.com/en-us/documentation/articles/machine-learning-apps-text-analytics/
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.pontis.hackathon.textanalytics.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * TopicAssignmentRecordV2
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T16:43:13.271+02:00")
public class TopicAssignmentRecordV2   {
  @SerializedName("documentId")
  private String documentId = null;

  @SerializedName("topicId")
  private String topicId = null;

  @SerializedName("distance")
  private Double distance = null;

  public TopicAssignmentRecordV2 documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Identifier for the document. Equates to the ID included in the input.
   * @return documentId
  **/
  @ApiModelProperty(example = "null", value = "Identifier for the document. Equates to the ID included in the input.")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public TopicAssignmentRecordV2 topicId(String topicId) {
    this.topicId = topicId;
    return this;
  }

   /**
   * The topic ID which the document has been assigned to.
   * @return topicId
  **/
  @ApiModelProperty(example = "null", value = "The topic ID which the document has been assigned to.")
  public String getTopicId() {
    return topicId;
  }

  public void setTopicId(String topicId) {
    this.topicId = topicId;
  }

  public TopicAssignmentRecordV2 distance(Double distance) {
    this.distance = distance;
    return this;
  }

   /**
   * Document-to-topic affiliation score between 0 and 1. The lower a distance score the stronger the topic affiliation is.
   * @return distance
  **/
  @ApiModelProperty(example = "null", value = "Document-to-topic affiliation score between 0 and 1. The lower a distance score the stronger the topic affiliation is.")
  public Double getDistance() {
    return distance;
  }

  public void setDistance(Double distance) {
    this.distance = distance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopicAssignmentRecordV2 topicAssignmentRecordV2 = (TopicAssignmentRecordV2) o;
    return Objects.equals(this.documentId, topicAssignmentRecordV2.documentId) &&
        Objects.equals(this.topicId, topicAssignmentRecordV2.topicId) &&
        Objects.equals(this.distance, topicAssignmentRecordV2.distance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, topicId, distance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopicAssignmentRecordV2 {\n");
    
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    topicId: ").append(toIndentedString(topicId)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

